### ISSUE TITLE
[Ошибка, 24.10.2016] Некорректное объявление класса

### ISSUE THREAD

**Issue by DmitryKuk** [IDB-15-15/interface#5]
Класс `MainWindow` некорректно объявлен в файле `mainwidnow.hpp` (и соотв. некорректно определены его методы в `mainwindow.cpp`): класс находится в глобальном пространстве имён.

Недостаточно объявить класс в пространстве, как это сделано в файле `mainwindow.hpp`:

``` c++
namespace Ui {
class MainWindow;
}
```

Далее следует объявление класса в глобальном пространстве имён, а в результате в `Ui` ничего не попадает.

Замечания:
- Класс не должен быть объявлен в глобальном пространстве имён + каком-то ещё.
- Класс вообще не должен быть объявлен в глобальном пространстве имён.
- Класс должен быть объявлен **только** в одном **(не глобальном)** пространстве имён.
  - _Если кому-то он понадобится в другом пространстве имён, он напишет `using namespace ns;` или `using ns::class_name;`_

См. соотв. пример: https://github.com/DmitryKuk/IDB-Examples/tree/master/files

**К чему это ведёт?** Ни к чему криминальному, просто не надо сразу делать из своего проекта нечитаемое Qt. :)

**Comment by DmitryKuk** [comment]
Серьёзно?
Вижу этот бред до сих пор: https://github.com/IDB-15-15/interface/blob/master/src/mainwindow.h
И тут такая же фигня: https://github.com/IDB-15-15/interface/blob/master/src/mainform.h
В обоих случаях зачем-то классы объявляются в Ui.

**Comment by kuzy000** [comment]
man qt

**Comment by TurtleDream** [comment]
Так в namespace или нет? Вам не кажется, что идея запихивать автоматически сгенерированные классы (с помощью moc) в отдельный namespace - это хорошая идея?

**Comment by DmitryKuk** [comment]
Отлично, что аргументированную позицию завезли. Плохо, что всё на уровне "кажется".
Я вижу в `main.cpp` строчку `Browser::MainWindow w;`, и у меня всё собирается. Если объясните, что на самом деле всё плохо, и работает только чудом -- пожалуйста, пишите в глобальном namespace.
*И да, с этим moc хватает проблем. Я не знаю, что там у него с namespace. Просто вижу, что это работает. Аргументируйте, почему (на ваш взгяд) не работает.*

Ещё плохо, что вы не читаете, что написано в issue. Посмотрите на строчки 13-15 `mainwindow.h` и подумайте, почему это бред. Аналогично проверьте остальные файлы.

Чтобы вы не сомневались, что это бред, я получил такие результаты:
```
src/main.cpp:6:29: error: variable has incomplete type 'Browser::Ui::MainWindow'
    Browser::Ui::MainWindow w;
src/mainwindow.h:14:7: note: forward declaration of 'Browser::Ui::MainWindow'
class MainWindow;
```

P.S. Станислав, вы всегда сначала заявляете, что работа сделана, а потом разгребаете?

**Comment by DmitryKuk** [comment]
Итак, люди. Моисеенко объяснил, в чём собака порылась. Issue с этого момента закрыта, но от вас, Станислав, требуется понимание происходящего.
